- name: Deploy to VPS
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.VPS_SSH_KEY }}
    debug: true
    ssh_options: |
      IdentitiesOnly=yes
      LogLevel=DEBUG3
    script: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      cd /var/www/html
      git pull origin main
      npm install
      npm run build
      pm2 restart nord-laundry-app