name: Deploy to Beget VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}     
          username: ${{ secrets.VPS_USER }}   
          key: ${{ secrets.VPS_SSH_KEY }}  
          debug: true  
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /var/www/html
            git pull -Xtheirs origin main
            npm install
            npm run build
            pm2 restart nord-laundry-app